// const express = require("express")
// const userRouter = require("./user.route")
// const cartRouter = require("./cart.route")
// const orderRouter = require("./order.route")
// const tokenRouter = require("./token.route")
// const bannerRouter = require("./banner.route")
// const cityRouter = require("./city.route")
// const stateRouter = require("./state.route")
// const countryRouter = require("./country.route")
// const restauranttypeRouter = require("./restaurant.type.route")
// const searchRouter = require("./search.route.js")
// const restaurantRouter = require("./restaurant.route")
// const foodRouter = require("./food.route")
// const router = express.Router()

// router.use("/user",userRouter)
// router.use("/cart",cartRouter)
// router.use("/order",orderRouter)
// router.use("/token",tokenRouter)
// router.use("/banner",bannerRouter)
// router.use("/city",cityRouter)
// router.use("/state",stateRouter)
// router.use("/country",countryRouter)
// router.use("/restaurant-type",restauranttypeRouter)
// router.use("/search",searchRouter)
// router.use("/restaurant",restaurantRouter)
// router.use("/food",foodRouter)

// module.exports = router